include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    avoid_function_literals_in_foreach_calls: false
    public_member_api_docs: false
    always_use_package_imports: false
    prefer_relative_imports: true